# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  projectDirectory: sample_project

jobs:
  - job: ios
    pool:
      vmImage: 'macos-latest'
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: ios
        projectDirectory: $(projectDirectory)

    - task: CopyFiles@2
      inputs:
        contents: '**/*.ipa'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
